apply 'https://github.com/endymion/appleseed/raw/master/templates/haml_gem.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/compass_gem.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/jquery_gem.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/rspec_gem.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/cucumber_gems.rb'

apply 'https://github.com/endymion/appleseed/raw/master/templates/bundle_install.rb'

apply 'https://github.com/endymion/appleseed/raw/master/templates/gitignore.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/haml.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/compass.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/jquery.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/rspec.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/cucumber.rb'
apply 'https://github.com/endymion/appleseed/raw/master/templates/root_controller.rb'