#apply 'http://github.com/endymion/appleseed/raw/master/templates/gitignore.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/haml.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/compass.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/remove_prototype.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/jquery.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/rspec.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/cucumber.rb'
#apply 'http://github.com/endymion/appleseed/raw/master/templates/root_controller.rb'

apply 'http://localhost/projects/appleseed/templates/gitignore.rb'
apply 'http://localhost/projects/appleseed/templates/haml.rb'
apply 'http://localhost/projects/appleseed/templates/compass.rb'
apply 'http://localhost/projects/appleseed/templates/remove_prototype.rb'
apply 'http://localhost/projects/appleseed/templates/jquery.rb'
apply 'http://localhost/projects/appleseed/templates/rspec.rb'
apply 'http://localhost/projects/appleseed/templates/cucumber.rb'
apply 'http://localhost/projects/appleseed/templates/root_controller.rb'