apply 'http://github.com/endymion/appleseed/raw/master/templates/gitignore.rb'
apply 'http://github.com/endymion/appleseed/raw/master/templates/haml.rb'
apply 'http://github.com/endymion/appleseed/raw/master/templates/compass.rb'
apply 'http://github.com/endymion/appleseed/raw/master/templates/jquery.rb'
apply 'http://github.com/endymion/appleseed/raw/master/templates/rspec.rb'
apply 'http://github.com/endymion/appleseed/raw/master/templates/cucumber.rb'
apply 'http://github.com/endymion/appleseed/raw/master/templates/root_controller.rb'