apply 'http://localhost/projects/appleseed/templates/haml_gem.rb'
apply 'http://localhost/projects/appleseed/templates/compass_gem.rb'
apply 'http://localhost/projects/appleseed/templates/jquery_gem.rb'
apply 'http://localhost/projects/appleseed/templates/rspec_gem.rb'
apply 'http://localhost/projects/appleseed/templates/cucumber_gems.rb'

apply 'http://localhost/projects/appleseed/templates/bundle_install.rb'

apply 'http://localhost/projects/appleseed/templates/gitignore.rb'
apply 'http://localhost/projects/appleseed/templates/haml.rb'
apply 'http://localhost/projects/appleseed/templates/compass.rb'
apply 'http://localhost/projects/appleseed/templates/jquery.rb'
apply 'http://localhost/projects/appleseed/templates/rspec.rb'
apply 'http://localhost/projects/appleseed/templates/cucumber.rb'
apply 'http://localhost/projects/appleseed/templates/root_controller.rb'